version: "3.7"

services:
  backend:
    build: 
      context: ./backend 
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:  
      - "8080:8080"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - frontend
      - backend

networks:
  backend:
  frontend: